#spring:
 # datasource:
 #   url: jdbc:h2:mem:testdb
 #   driverClassName: org.h2.Driver
 #   username: sa
 #   password:
 # h2:
 #   console:
 #     enabled: true
 #     path: /h2-console
 # jpa:
 #   show-sql: true
 #   open-in-view: true

spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/api_calls
    username: desa1234
    password: desa1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop  # crea las tablas y las dropea cada vez que hay un run de la app